### ISSUE TITLE
No way to turn off bintray

### ISSUE THREAD

**Issue by jefferai** [hashicorp/middleman-hashicorp#10]
As a lay user, there doesn't appear to be a way to turn off the Bintray integration. This causes a problem when attempting to build the site (as opposed to using middleman server) in a fork. The use-case in this instance is to build a gh-pages hosted copy of the fork's documentation to make review easier. Two minor additions (one to pull in middleman-deploy in the Gemfile, the other to enable it with defaults in config.rb) otherwise make the gh-pages deployment easy as pie.

**Comment by armon** [comment]
@sethvargo Is this something you could look into?

**Comment by sethvargo** [comment]
Hi @jefferai 

Thank you for opening an issue. All our projects have been updated to use `bintray_enabled` set to an environment variable (thus defaulting to false), so you can build locally now without bintray hassle.

I think adding the `middleman-deploy` or `middleman-github` plugins would be overkill. While I understand you may want to build a hosted copy of the documentation, this is not something we would like to active encourage at this time. Thanks!

**Comment by jefferai** [comment]
@sethvargo Understood that adding them centrally is overkill, but they're useful to be able to add for individual forks, e.g. when working on https://github.com/hashicorp/vault/issues/125 to share proposed APIs :-)

Thanks!
