### ISSUE TITLE
Extract bintray support into separate gem

### ISSUE THREAD

**Issue by promisedlandt** [hashicorp/middleman-hashicorp#15]
Hey,

I'm using this project for the nice bintray support, but I don't use most of the other features.

If I extract the bintray support into a separate gem, would you move it to the Hashicorp Github?
I'll happily add a pull request on this repository to add the necessary new configuration / deletion of bintray stuff.

**Comment by sethvargo** [comment]
Hi @promisedlandt 

Thank you for opening an issue. While this project is "open source" in the sense that the source is open, we are not really looking for contributions at this time. You're more than welcome to borrow the Bintray pieces for your own project in your own namespace, but I don't think we will bring that in as a dependency :smile:.Thanks!
