### ISSUE TITLE
Mega Nav: Larger link area for dropdown

### ISSUE THREAD

**Issue by jasoncostello** [hashicorp/middleman-hashicorp#42]
Currently, only the caret is a link for the dropdown. @captainill recommended adding "The HashicCorp Suite" to be clickable as well. 

<img width="419" alt="screen shot 2017-04-05 at 7 42 43 pm" src="https://cloud.githubusercontent.com/assets/416727/24735597/9462029e-1a38-11e7-82d5-b88a566a4600.png">

**Comment by sethvargo** [comment]
👍

**Comment by ryon** [comment]
I've addressed this in https://github.com/hashicorp/middleman-hashicorp/pull/45/commits/95b26818f2f194a5678bddce0040c123c6fa06ba by including the text and logo in the `<button>` and tweaking the styling a bit to make everything look the same.

**Comment by jasoncostello** [comment]
Fixed in #45 by @ryon 🥇
