### ISSUE TITLE
terraform color in meganav is incorrect

### ISSUE THREAD

**Issue by captainill** [hashicorp/middleman-hashicorp#43]
@jasoncostello Heads up for the next release to fix the TF color.

<img width="702" alt="screen shot 2017-04-07 at 1 31 57 pm" src="https://cloud.githubusercontent.com/assets/438899/24818809/ca174fe8-1b96-11e7-9917-8a2e4c1ea1aa.png">

**Comment by sethvargo** [comment]
We should consider using the "new" svgs which are styleable via CSS to make it easy to change these.
