### ISSUE TITLE
Update outdated Nomad logo

### ISSUE THREAD

**Issue by jasoncostello** [hashicorp/middleman-hashicorp#44]
### Is:

<img width="216" alt="screen shot 2017-05-16 at 5 49 26 pm" src="https://cloud.githubusercontent.com/assets/416727/26134995/4c6de7b0-3a67-11e7-9d96-1932fd76d1fb.png">

### Should be
<img width="268" alt="screen shot 2017-05-16 at 6 41 59 pm" src="https://cloud.githubusercontent.com/assets/416727/26135019/6a519b82-3a67-11e7-885c-7bf7b75e2b16.png">

**Comment by sethvargo** [comment]
@jasoncostello I think the logo on nomadproject.io needs to be updated as well.

**Comment by jasoncostello** [comment]
@sethvargo :+1: I'll update it when I PR the middleman bump
