### ISSUE TITLE
Anchor generation is problematic for list-items

### ISSUE THREAD

**Issue by ryanuber** [hashicorp/middleman-hashicorp#6]
Currently, any code block inside of an `<li>` seems to be automatically surrounded by an inner anchor, which links to itself. The `list_item` function seems to be what is doing this, by injecting the following:

``` erb
<a name="#{anchor}" /><a href="##{anchor}">#{container}</a>
```

This causes problems for both Consul and Serf's documentation. For example, visit [this url](https://consul.io/docs/agent/http/agent.html) and click on the `/v1/agent/self` link. You are directed to an anchor, which is on the same line as the link you clicked.

Our source actually contains valid anchors and links to them. By commenting out the `list_item` function entirely, the desired link/anchor is restored.

I like how these links get auto-generated, but I don't think we will want to automatically override if there is already some kind of anchor there.

@sethvargo, any thoughts? I'm down to help fixing up Consul's docs if that's what you think is required, but I'm wondering if we have too much "magic" going on in here. Maybe there is a way we can check for a leading anchor before automatically inserting a new one?

**Comment by sethvargo** [comment]
Yea I think we need to check if an anchor already exists, but I'm not sure if we'll have enough "scope" at that point. I can look into it more tomorrow or Monday.

**Comment by ryanbreen** [comment]
I created a PR to address the proximate issue, but I'm also unsure about the general approach of auto-creating both an anchor and a link to that anchor.  From a user's perspective, a link that takes you to where you already are seems like a jarring user experience (odds are, you jump some percentage of window height up or down, enough to be disorienting without actually taking you anywhere new).

Auto-creating the anchor is cool, but what's the use case for creating a sibling node that amounts to a self-referential link to that anchor?

**Comment by ryanuber** [comment]
I think the intent was to be able to link others to specific parts of a documentation page, and having the link there makes it easy to right-click and copy the link. There might also be some kind of SEO impact, but Im not sure on that.

**Comment by ryanbreen** [comment]
Makes sense.  If anchor name is a function of the contents of <code>, it's still pretty easy to construct an anchor link even without copy-paste.  Not a huge deal, and maybe it's just me that finds the current behavior disorienting.

**Comment by sethvargo** [comment]
@ryanbreen @ryanuber took longer than I had anticipated because of some middleman issues, but #8 should fix the issue. I verified this locally.

**Comment by ryanuber** [comment]
This is deployed now on consul.io!

**Comment by ryanbreen** [comment]
Would you consider reopening this one?  The fix leads to inconsistent behavior on something like http://www.consul.io/docs/agent/options.html.  Note that only `<li>`s which do not contain links are auto-hyperlinked while all others are left bare.

If we check whether the `<li>` starts with a link rather than contains a link, that would address the original report while leading to consistent linking behavior on http://www.consul.io/docs/agent/options.html.

**Comment by ryanuber** [comment]
So this is what my original "too much magic" thought was about earlier. Even if this conditional anchor generation works flawlessly, it still makes the UX inconsistent. Some anchors will go to the targeted section, while others simply anchor to exactly where the `<code>` section appeared. @ryanbreen sounds like there are cases where we are still inconsistent, so I'll reopen this. @sethvargo, what do you think? Should we continue down the auto-anchor path? Any other ideas?

**Comment by sethvargo** [comment]
The auto-anchor was primarily for packer. Let me think a bit

**Comment by ryanbreen** [comment]
Ok, for the time being, I'll stick with manual anchoring of the Consul options so that we get consistent behavior there.
